import { NextResponse } from "next/server";
import db from "@/lib/db";
import { getCurrentUser, revokeUserSessions } from "@/lib/auth";
import { verifyCsrf } from "@/lib/csrf";
import { hashPassword } from "@/lib/password";
import { audit } from "@/lib/audit";
import { clientIp } from "@/lib/security";
import { z } from "zod";
export const runtime="nodejs";
type Context={params:Promise<{id:string}>};
const updateSchema=z.object({username:z.string().trim().min(3).max(32).regex(/^[a-zA-Z0-9_-]+$/).optional(),email:z.string().trim().email().max(254).optional(),role:z.enum(["USER","ADMIN"]).optional(),status:z.enum(["ACTIVE","SUSPENDED"]).optional(),uploadEnabled:z.boolean().optional(),quotaBytes:z.number().int().positive().optional(),newPassword:z.string().min(12).max(128).optional()});
export async function PATCH(request:Request,{params}:Context){const admin=await getCurrentUser();if(!admin||admin.role!=="ADMIN")return NextResponse.json({error:"Forbidden"},{status:403});if(!(await verifyCsrf(request)))return NextResponse.json({error:"Invalid request"},{status:403});const {id}=await params;const target=db.prepare("SELECT * FROM users WHERE id=?").get(id) as any;if(!target)return NextResponse.json({error:"User not found"},{status:404});try{const data=updateSchema.parse(await request.json());if(target.is_primary&&(data.role==="USER"||data.status==="SUSPENDED"))return NextResponse.json({error:"The Primary Administrator is protected"},{status:409});if(data.newPassword){db.prepare("UPDATE users SET password_hash=? WHERE id=?").run(await hashPassword(data.newPassword),id);revokeUserSessions(id);audit("PASSWORD_RESET",admin.id,id,{},clientIp(request));}const fields:string[]=[];const values:unknown[]=[];const map:any={username:data.username,email:data.email,role:data.role,status:data.status,upload_enabled:data.uploadEnabled===undefined?undefined:Number(data.uploadEnabled),quota_bytes:data.quotaBytes};for(const [key,value] of Object.entries(map)){if(value!==undefined){fields.push(`${key}=?`);values.push(value)}}if(fields.length){values.push(id);db.prepare(`UPDATE users SET ${fields.join(",")} WHERE id=?`).run(...values);audit(data.role?"ROLE_CHANGED":data.quotaBytes?"STORAGE_QUOTA_CHANGED":data.status?"USER_STATUS_CHANGED":"USER_UPDATED",admin.id,id,{fields:fields.map(f=>f.split("=")[0])},clientIp(request));}return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message.includes("UNIQUE")?"Username or email already in use":"Invalid user update"},{status:400});}}
export async function DELETE(request:Request,{params}:Context){const admin=await getCurrentUser();if(!admin||admin.role!=="ADMIN")return NextResponse.json({error:"Forbidden"},{status:403});if(!(await verifyCsrf(request)))return NextResponse.json({error:"Invalid request"},{status:403});const {id}=await params;const target=db.prepare("SELECT id,is_primary FROM users WHERE id=?").get(id) as any;if(!target)return NextResponse.json({error:"User not found"},{status:404});if(target.is_primary)return NextResponse.json({error:"The Primary Administrator is protected"},{status:409});db.prepare("DELETE FROM users WHERE id=?").run(id);audit("USER_DELETED",admin.id,id,{},clientIp(request));return NextResponse.json({ok:true});}

