"use client";
import { useMemo,useState } from "react";
import ThemeToggle from "./theme-toggle";

type FileItem={id:string;original_name:string;size_bytes:number;mime_type:string;created_at:string};
type Notice={text:string;error:boolean};
const fmt=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(2)} GB`;
async function csrf(){const response=await fetch("/api/auth/csrf");return (await response.json()).token as string;}

export default function FileDashboard({user,initialFiles,initialUsed,maxUpload,site}:{user:{username:string;email:string;role:string;quota:number;uploadEnabled:boolean;theme:"light"|"dark"};initialFiles:FileItem[];initialUsed:number;maxUpload:number;site:string}){
  const [files,setFiles]=useState(initialFiles),[used,setUsed]=useState(initialUsed),[query,setQuery]=useState(""),[sort,setSort]=useState("new"),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice|null>(null);
  const filtered=useMemo(()=>files.filter(file=>file.original_name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="name"?a.original_name.localeCompare(b.original_name):sort==="size"?b.size_bytes-a.size_bytes:new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[files,query,sort]);
  const pct=user.quota>0?Math.round((used/user.quota)*100):100,barPct=Math.min(100,pct),remaining=Math.max(0,user.quota-used),overQuota=used>user.quota,full=used>=user.quota;
  async function upload(list:FileList|null){
    if(!list||!list.length||!user.uploadEnabled)return;
    const selected=Array.from(list),oversized=selected.find(file=>file.size>maxUpload),total=selected.reduce((sum,file)=>sum+file.size,0);
    if(oversized){setNotice({text:`${oversized.name} is too large. Maximum file size is ${fmt(maxUpload)}.`,error:true});return;}
    if(total>remaining){setNotice({text:`You selected ${fmt(total)}, but only ${fmt(remaining)} remains. Choose fewer or smaller files.`,error:true});return;}
    setBusy(true);setNotice(null);const token=await csrf();
    for(const file of selected){const form=new FormData();form.append("file",file);await new Promise<void>(resolve=>{const xhr=new XMLHttpRequest();xhr.open("POST","/api/files");xhr.setRequestHeader("x-csrf-token",token);xhr.onload=()=>{try{const body=JSON.parse(xhr.responseText);if(xhr.status>=200&&xhr.status<300){setFiles(previous=>[body.file,...previous]);setUsed(previous=>previous+file.size)}else setNotice({text:body.error||"Upload failed",error:true})}catch{setNotice({text:"Upload failed",error:true})}resolve()};xhr.onerror=()=>{setNotice({text:"Upload failed",error:true});resolve()};xhr.send(form);});}
    setBusy(false);
  }
  async function remove(id:string){if(!confirm("Delete this file permanently?"))return;const response=await fetch(`/api/files/${id}`,{method:"DELETE",headers:{"x-csrf-token":await csrf()}});if(response.ok){const item=files.find(file=>file.id===id);setFiles(files.filter(file=>file.id!==id));setUsed(used-(item?.size_bytes||0));setNotice({text:"File deleted",error:false});}}
  async function rename(id:string,name:string){const response=await fetch(`/api/files/${id}`,{method:"PATCH",headers:{"content-type":"application/json","x-csrf-token":await csrf()},body:JSON.stringify({name})});if(response.ok){const updated=await response.json();setFiles(files.map(file=>file.id===id?{...file,original_name:updated.file.original_name}:file));setNotice({text:"File renamed",error:false});}}
  return <div>
    <header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4 md:px-10"><div><span className="text-sm text-slate-400">{site}</span><span className="mx-2 text-slate-300">/</span><b className="text-sm">My files</b></div><div className="flex items-center gap-3"><ThemeToggle initialTheme={user.theme}/><form action="/api/auth/logout" method="post"><button className="text-sm font-semibold text-slate-500">Sign out</button></form></div></header>
    <div className="mx-auto max-w-6xl p-5 md:p-10">
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Personal vault</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Your files</h1><p className="mt-1 text-sm text-slate-500">Everything you keep here is encrypted automatically.</p></div><label className={`button green ${(!user.uploadEnabled||busy||full)?"pointer-events-none opacity-60":""}`}>＋ {busy?"Uploading…":"Upload files"}<input className="hidden" type="file" multiple disabled={!user.uploadEnabled||busy||full} onChange={event=>upload(event.target.files)}/></label></div>
      {(overQuota||full)&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><b>{overQuota?"You have used too much storage.":"Your storage is full."}</b><p className="mt-1 text-sm">New uploads are blocked. Delete files or ask an administrator to increase your quota.</p></div>}
      <div className="mb-7 grid gap-4 md:grid-cols-3"><div className="card p-5 md:col-span-2"><div className="flex justify-between text-sm"><b>Storage used</b><span className="text-slate-500">{fmt(used)} of {fmt(user.quota)}</span></div><div className="mt-4 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${full?"bg-red-500":pct>80?"bg-orange-400":"bg-emerald-500"}`} style={{width:`${barPct}%`}}/></div><p className="mt-3 text-xs text-slate-400">{pct}% used · {overQuota?`${fmt(used-user.quota)} over quota`:`${fmt(remaining)} remaining`} · {fmt(maxUpload)} max per file</p></div><div className="card flex items-center gap-3 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-mint text-vault">✦</span><div><b className="block text-sm">Private by default</b><span className="text-xs text-slate-400">AES-256-GCM encrypted</span></div></div></div>
      {notice&&<div className={`mb-4 rounded-lg p-3 text-sm ${notice.error?"bg-red-50 text-red-800":"bg-emerald-50 text-emerald-800"}`}>{notice.text}</div>}
      <div className="card overflow-hidden"><div className="flex flex-wrap gap-3 border-b border-slate-100 p-4"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="⌕  Search files…" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm md:w-72"/><select value={sort} onChange={event=>setSort(event.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="new">Newest first</option><option value="name">Name</option><option value="size">Largest</option></select></div>{filtered.length===0?<div className="p-14 text-center"><div className="text-3xl">▣</div><b className="mt-3 block">No files yet</b><p className="mt-1 text-sm text-slate-400">Upload your first file to get started.</p></div>:<div className="divide-y divide-slate-100">{filtered.map(file=><div key={file.id} className="flex items-center gap-3 p-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-slate-50 text-slate-500">{file.mime_type.startsWith("image/")?"▧":"▤"}</span><div className="min-w-0 flex-1"><a href={`/api/files/${file.id}`} className="block truncate text-sm font-semibold hover:text-vault">{file.original_name}</a><span className="text-xs text-slate-400">{fmt(file.size_bytes)} · {new Date(file.created_at).toLocaleDateString()}</span></div>{["image/","video/","audio/","application/pdf"].some(prefix=>file.mime_type.startsWith(prefix))&&<a className="text-xs font-semibold text-slate-500" href={`/api/files/${file.id}?preview=1`} target="_blank">Preview</a>}<button onClick={()=>rename(file.id,prompt("New filename",file.original_name)||file.original_name)} className="text-xs font-semibold text-slate-500">Rename</button><a href={`/api/files/${file.id}`} className="text-xs font-semibold text-vault">Download</a><button onClick={()=>remove(file.id)} className="text-xs font-semibold text-red-500">Delete</button></div>)}</div>}</div>
    </div>
  </div>;
}
