import { NextResponse } from "next/server";
import db, { setSetting, getSetting } from "@/lib/db";
import { setupSchema } from "@/lib/validation";
import { hashPassword } from "@/lib/password";
import { audit } from "@/lib/audit";
import { clientIp, randomId, rateLimit } from "@/lib/security";
import { createSession } from "@/lib/auth";
export const runtime = "nodejs";
export async function POST(request: Request){if(getSetting("configured","false")==="true") return NextResponse.json({error:"Vaultify is already configured"},{status:409});if(!rateLimit(`setup:${clientIp(request)}`,5)) return NextResponse.json({error:"Too many attempts"},{status:429});try{const raw=await request.json();const data=setupSchema.parse({...raw,defaultQuotaBytes:Number(raw.defaultQuotaBytes),maxUploadBytes:Number(raw.maxUploadBytes)});const existing=db.prepare("SELECT id FROM users LIMIT 1").get();if(existing) return NextResponse.json({error:"Vaultify is already configured"},{status:409});const id=randomId();const passwordHash=await hashPassword(data.password);db.exec("BEGIN IMMEDIATE");try{db.prepare("INSERT INTO users(id,username,email,password_hash,role,is_primary,quota_bytes,created_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP)").run(id,data.username,data.email,passwordHash,"ADMIN",1,data.defaultQuotaBytes);setSetting("configured","true");setSetting("website_name",data.websiteName);setSetting("default_quota_bytes",String(data.defaultQuotaBytes));setSetting("max_upload_bytes",String(data.maxUploadBytes));setSetting("public_registration",String(data.publicRegistration));audit("SETUP_COMPLETED",id,id,{websiteName:data.websiteName},clientIp(request));db.exec("COMMIT");}catch(error){db.exec("ROLLBACK");throw error}const user=db.prepare("SELECT * FROM users WHERE id=?").get(id) as never;await createSession(user,clientIp(request));return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error&&e.message.includes("UNIQUE")?"Username or email already in use":"Invalid setup details"},{status:400});}}
